### ISSUE TITLE
Xcode and arm cortex m0 mcu development

### ISSUE THREAD

**Issue by mstrouse** [samdmarshall/QandA#2]
Hi,
Have you ever used Xcode to do embedded micro-controller development (compiling and linking to an elf file) using gcc tools (https://launchpad.net/gcc-arm-embedded) for arm cortex parts?
BR,
Marshall

**Comment by samdmarshall** [comment]
Hi, this is a really good question and as i started to draft a response I realized this could easily become a blog post that talks about how to get third party toolchains integrated with Xcode's build system. So I'd like to write that up and link back to this post if that is alright with you.

**Comment by mstrouse** [comment]
That would be awesome.  I'm struggling, but making some (small) progress.

So there are a couple of issues at play here. One is that there are very few good IDEs for OS X (Xcode being one). And of those good IDEs, none support embedded development (think mcu's) ... sorry I don't consider Eclipse to be a good IDE on OS X. Crossworks is okay, but it relies on an older version of Qt. Ick. Above all, I'm tired of using Win platform to develop embedded firmware. The unfortunate upshot to all of this is that we have this great IDE (in Xcode) but Apple has no interest (and sees no value) in supporting embedded development. It's Apple's world, we just live in it ...

I have found another person that has shared some pertinent information ... long story short, look at Intel's ICC compiler / linker plug-ins for Xcode. That's the template for adding gcc for arm cortex mX parts.

**Comment by mstrouse** [comment]
Hi Samantha,
So I thought I would bring you up to speed ... I've been able to hack the ICC C compiler plugin from Intel to be able to call the gnu gcc toolset for arm cortex mX parts. I have compiling (so far a simple C program) and linking code into a bit of working object code.  Still needs some work, but it's getting there. I'm temporarily moving off to work on the gdb debugger <-> jlink interface.  Do you want to collaborate / look at some of what I've done? Marsh. 

```
 On Tuesday, August 18, 2015 5:56 PM, Samantha Marshall <notifications@github.com> wrote:
```

 Hi, this is a really good question and as i started to draft a response I realized this could easily become a blog post that talks about how to get third party toolchains integrated with Xcode's build system. So I'd like to write that up and link back to this post if that is alright with you.—

**Comment by samdmarshall** [comment]
I have the outline and main details of this done, I'm going to go through this again now I can do it with Xcode 7.1 and check for any inconsistencies and new things with the build system. Sorry this is taking so long, it is one of the more involved topics.

**Comment by mstrouse** [comment]
One quick question … does this use (or did you create) a new Platform type?

As I’ve worked through this separately, I’ve come to the conclusion that the best way to support MCU (embedded arm) development is with a new Platform (and by not relying on Mac OS / iPhone OS platforms). I’m currently off researching how to support debugging with a JLink. BR, Marshall.

**Comment by samdmarshall** [comment]
Yup! The process for doing this would be via adding a new platform to the developer directory in xcode.

**Comment by mstrouse** [comment]
Grrr... I did this, but ran into 2 problems: 1) All of the provisioning stuff getting in the way - which is not strictly needed for MCU work, and 2) I ran into an Xcode crash related to extendedplatforminfo (and couldn't get nicely/completely around it). I'm bummed you figured it out ;-)

**Comment by mstrouse** [comment]
Any update here?

**Comment by mstrouse** [comment]
Let me try ... let me try ... ) 

```
 On Monday, September 21, 2015 3:34 PM, Samantha Marshall <notifications@github.com> wrote:
```

 Yup! The process for doing this would be via adding a new platform to the developer directory in xcode.—

**Comment by mstrouse** [comment]
Just checking in ... any update?

As an aside, I am able to successfully compile / link code (and program devices via JLink) for various arm cortex-m devices from TI and Freescale, but still can't debug. I think? that will only be possible from a proper platform. Marsh.

**Comment by james919** [comment]
@mstrouse - were you able to get this working? I realize this was a while ago, but I'm also very interested in using Xcode for Cortex-Mx development. I've been able to move from Windows-based tools for the STM32F4 and PSoC 4 (BLE) over to Eclipse on Mac OS X (macOS soon), using makefile-based projects, but I'd really love to move everything into Xcode.
