### ISSUE TITLE
Multiple apps off of one main app

### ISSUE THREAD

**Issue by DojiStar** [samdmarshall/QandA#3]
Hi Samantha!

I ran across your blog and had a question for you. I have a project which requires multiple skinned apps off of the main project and then a couple of partner apps which contain customization of the main app.

So..

I have the main app then 10-20 apps which are just skins of that main app (assets, strings, colors), and then 2-3 apps based on the main app but contain specific code changes just for those apps.

All of the code is shared and I turn things on/off based on feature flags / builds settings and resource packages.

Hope that makes sense.

Have you ever done anything like this? I am trying to determine the best way to handle this from an xcode / project perspective. Right now the plan is to take the main project and then generate the other project files dynamically. Is that crazy talk? 

Any ideas? or pointers?

Thanks!

**Comment by samdmarshall** [comment]
Hey, so I wrote up a post related to this, [http://pewpewthespells.com/blog/using_xcode_targets.html](http://pewpewthespells.com/blog/using_xcode_targets.html) and wondering if this answers your question or if you have additional questions about this.

**Comment by DojiStar** [comment]
Great and thank you!

Let's say I have a Dev build and app store build, the dev build has a debug
view but for the app store build, I don't want it to even compile since its
for dev/debug only. What's the best way to deal with this? Can I avoid
using #defines to remove this?

Thanks!
Angelo

On Sun, Sep 20, 2015 at 9:14 AM, Samantha Marshall <notifications@github.com

> wrote:
> 
> Hey, so I wrote up a post related to this,
> http://pewpewthespells.com/blog/using_xcode_targets.html and wondering if
> this answers your question or if you have additional questions about this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samdmarshall/QandA/issues/3#issuecomment-141804027.

## 

-Ang

**Comment by samdmarshall** [comment]
I would use `#if DEBUG` for that. You could do it without that but it would probably get more complicated the more you were dealing with the build system to solve this problem.

**Comment by DojiStar** [comment]
That's what I'd thought you'd say :).  Another question coming up is how to
handle AppleTV and iPad/iPhone builds using a core set of code for both
platforms? Different project files? A target? Have you given any thought to
this?

Thanks!
Angelo

On Tue, Sep 22, 2015 at 6:02 PM, Samantha Marshall <notifications@github.com

> wrote:
> 
> I would use #if DEBUG for that. You could do it without that but it would
> probably get more complicated the more you were dealing with the build
> system to solve this problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samdmarshall/QandA/issues/3#issuecomment-142465903.

## 

-Ang

**Comment by samdmarshall** [comment]
This was the premise of the blog post i linked in the initial reply. There are some things you will have to watch out for, but you can definitely share targets for the various platforms so you can have a single target for your core code.
