### ISSUE TITLE
A few real small typos — Migrating Code Signing

### ISSUE THREAD

**Issue by jdhealy** [samdmarshall/QandA#6]
Noticed a few real small typos in [Migrating Code Signing Configurations to Xcode 8](http://pewpewthespells.com/blog/migrating_code_signing.html):
- Missing period after `validated` in `embedded into the executable binary to allow for it to be validated This will ensure`.
- This sentence might have landed wrong: `So for the value of CODE_SIGN_IDENTITY is represented by the following command`.
- Also, to be super pedantic, `Development - Deploying an application to your devices` and it's following bullet should probably have an em dash: `—` 🙃

![kermit-typing-furiously](https://cloud.githubusercontent.com/assets/782837/18284274/6313f53c-7437-11e6-836c-6c99d2ecb55d.gif)

Excellent article — such an immense help!

**Comment by samdmarshall** [comment]
Thanks, these should be fixed now.
