### ISSUE TITLE
micro and default keybindings

### ISSUE THREAD

**Issue by dg01d** [samdmarshall/QandA#7]
Hi Sam,

Your writing exposed me to micro, I'd not heard of the editor and was pleasantly surprised at how full featured it is.

How did you finalise key bindings in macOS to make it more useful? The conflict of keybindings with mac's defaults is a real 'boundary issue', windows keep appearing & disappearing, I can't (couldn't) move by word or to EOL.

Anyway, thanks for reading this, I'd be really glad if you could offer some wisdom from the field.

**Comment by samdmarshall** [comment]
I don't use split windows in micro, and end up using a lot of tabs. you can check out my micro config as [part of my dotfiles](https://github.com/samdmarshall/dotfiles/blob/master/micro/bindings.json) I will either navigate by mouse for big jumps or option+arrow for a small incremental jump. Part of this is how i write and edit text, and part of this is just me being happy with micro's defaults (before this i was using coderunner and textmate). I've tried some other editors and was extremely unhappy with their default keybindings or the difficulty involved with remapping keys, so micro is filling the niche the best for me. It doesn't fulfill everything i want, but the developer and community are active and receptive to new ideas and patches (i learned go-lang and lua submitting patches to this project).
